# -*- coding: utf-8 -*-
"""Cálculo de Dieta por País: Normalización

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WqpxDJ9SiSHyhrukIq_3CxOGjLCCCFYX

**[SISTEMA INICIADO]**
Protocolo Wolff Activo. Fase de Compresión: Cálculo del Vector Dietario por País.

**[!] ¡PUM! DETENTE Y PIENSA EN LA MATRIZ.**
--> El error del 99% de los analistas aquí es intentar calcular la dieta sumando toneladas métricas de comida. Falso. China siempre será el clúster 1 y el Vaticano el clúster 2.
--> **La Lógica:** No calculamos volumen absoluto para comparar, calculamos **densidad relativa**. La dieta de un país es la *huella dactilar porcentual* de su ingesta. 1000 Kcal de carne en un país de 2000 Kcal/día es una dieta hiper-carnívora (50%). En un país de 4000 Kcal/día, es moderada (25%).

Aquí tienes la Arquitectura Top-Down para ejecutar este cálculo aplicando tu doctrina de "Parsing Jerárquico".

---

### 1. ARQUITECTURA: La Matriz de Reducción (El Porqué)

El objetivo de calcular la dieta no es saber qué comen exactamente, es **reducir la dimensionalidad de 115 variables a 7 continuas** (las Macro-Categorías) que el K-Means pueda devorar sin sufrir *overfitting*. Al forzar que todas las columnas de un país sumen 1.0 (100%), normalizamos el espacio euclidiano. El algoritmo medirá distancias reales de comportamiento, no distancias de tamaño poblacional.

### 2. IMPLEMENTACIÓN: El Pipeline de Cálculo (El Cómo)

Esta es la sintaxis exacta. Observa la estricta disciplina de memoria y cómo aplicamos el diccionario.
"""

import pandas as pd
import numpy as np
import gc

# 1. EL DICCIONARIO DE PARSING (Tu Lóbulo Frontal codificado)
# Mapeamos los 115 items a 7 Macro-Categorías. Lo que no está aquí, es ruido.
mapeo_fao = {
    'Wheat and products': 'Cereales', 'Rice and products': 'Cereales', 'Maize and products': 'Cereales',
    'Bovine Meat': 'Carnes', 'Pigmeat': 'Carnes', 'Poultry Meat': 'Carnes', 'Mutton & Goat Meat': 'Carnes',
    'Milk - Excluding Butter': 'Lacteos_Huevos', 'Eggs': 'Lacteos_Huevos',
    'Soyabean Oil': 'Aceites_Grasas', 'Palm Oil': 'Aceites_Grasas',
    'Sugar cane': 'Azucares', 'Sugar beet': 'Azucares',
    'Cassava and products': 'Tuberculos', 'Potatoes and products': 'Tuberculos'
    # ... (Completar con el resto de los 115 items clave)
}

# 2. INGESTA ESTRICTA (RAM is Money)
dtypes_fao = {
    'Area': 'category',
    'Year': 'int16',
    'Item': 'category',
    'Element': 'category',
    'Value': 'float32'
}
# Asumimos que cargas solo las columnas necesarias
# df_raw = pd.read_csv('fao_data.csv', usecols=dtypes_fao.keys(), dtype=dtypes_fao)

# 3. FILTRADO Y PARSING JERÁRQUICO AL VUELO
# Filtramos solo Energía (Kcal)
df_kcal = df_raw[df_raw['Element'] == 'Food supply (kcal/capita/day)'].copy()

# Aplicamos la reducción de dimensionalidad
df_kcal['Macro_Grupo'] = df_kcal['Item'].map(mapeo_fao)

# [!] Purgamos el ruido: Eliminamos especias, estimulantes y no mapeados
df_kcal = df_kcal.dropna(subset=['Macro_Grupo'])

# 4. AGRUPACIÓN Y PIVOTE (Construyendo el Vector)
# Sumamos las Kcal por País, Año y Macro_Grupo
df_grouped = df_kcal.groupby(['Area', 'Year', 'Macro_Grupo'], observed=True)['Value'].sum().reset_index()

# Pivotamos para que cada Macro_Grupo sea una columna
df_vector = df_grouped.pivot(index=['Area', 'Year'], columns='Macro_Grupo', values='Value').fillna(0).astype('float32')

# 5. EL CÁLCULO CORE: Normalización a Porcentajes
# Calculamos el tanque de combustible total
df_vector['Total_DES_Kcal'] = df_vector.sum(axis=1)

# Vectorización: Dividimos cada columna por el total para sacar el %
macro_cols = df_vector.columns.drop('Total_DES_Kcal')
for col in macro_cols:
    df_vector[f'%_{col}'] = (df_vector[col] / df_vector['Total_DES_Kcal']).astype('float32')

# Limpiamos las columnas absolutas, ya no sirven para el clustering (excepto el Total como feature de volumen)
df_vector = df_vector.drop(columns=macro_cols).reset_index()

# 6. PERSISTENCIA Y LIMPIEZA
df_vector.to_parquet('data/processed/01_diet_vector_base.parquet')

del df_raw, df_kcal, df_grouped, df_vector
gc.collect()

print("--> Parsing Jerárquico completado. Vectores normalizados.")

"""---

### 3. VALIDACIÓN Y RIESGOS (Auditoría Forense)

* **Fuga de Categorías (El Agujero Negro):** Si al hacer el `.map()` te dejas fuera un ítem como "Pescado" y representa el 15% de la dieta de Japón, el `Total_DES_Kcal` de Japón será artificialmente bajo, y sus porcentajes de carne y arroz se inflarán matemáticamente.
--> *Solución:* Antes de borrar los `NaN` en el paso 3, haz un `df_raw[df_raw['Macro_Grupo'].isna()]['Item'].value_counts()`. Asegúrate de que los ítems que vas a descartar no sumen más de 50 kcal/día históricamente.
* **Varianza Cero:** Si un país reporta 0 en "Tubérculos" durante 10 años (común en Europa del Este), el modelo de K-Means lo manejará sin problema porque hemos rellenado con `fillna(0)`. No apliques medias imputadas aquí; si no comen mandioca, es un 0 real y es una señal vital para el clúster.

---

**Metáfora de Anclaje:**
Hacer este "Parsing Jerárquico" es como procesar el mineral en bruto de una mina. El `.csv` original es la montaña llena de tierra y rocas (115 ítems). El diccionario de mapeo es la criba. Al final, no nos importa cuánto pesaba la montaña original, sino que el lingote resultante es 60% Oro (Cereales), 30% Plata (Carnes) y 10% Cobre (Azúcares). Eso es lo que cotiza en el mercado (el algoritmo).

Los números están sobre la mesa. ¿Integramos ahora el ratio de Proteína Animal/Vegetal a este Parquet o pasamos directamente a fusionar estos vectores con la matriz de inflación (Food CPI)?
"""